"""Android TV application database."""

APP_DATABASE = {
    "org.smarttube.beta": {
        "name": "SmartTube",
        "icon": "smarttube.png",
        "brand_color": "#FF0000",
        "category": "Video",
        "developer": "SmartTube",
        "supports_metadata": True,
        "supports_ads": True,
        "supports_live": True,
    },
    "com.google.android.youtube.tv": {
        "name": "YouTube",
        "icon": "youtube.png",
        "brand_color": "#FF0000",
        "category": "Video",
        "developer": "Google",
        "supports_metadata": True,
        "supports_ads": True,
        "supports_live": True,
    },
    "com.google.android.youtube": {
        "name": "YouTube",
        "icon": "youtube.png",
        "brand_color": "#FF0000",
        "category": "Video",
        "developer": "Google",
        "supports_metadata": True,
        "supports_ads": True,
        "supports_live": True,
    },
    "com.netflix.ninja": {
        "name": "Netflix",
        "icon": "netflix.png",
        "brand_color": "#E50914",
        "category": "Streaming",
        "developer": "Netflix",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": False,
    },
    "tv.plex.android": {
        "name": "Plex",
        "icon": "plex.png",
        "brand_color": "#E5A00D",
        "category": "Media",
        "developer": "Plex",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": True,
    },
    "com.plexapp.android": {
        "name": "Plex",
        "icon": "plex.png",
        "brand_color": "#E5A00D",
        "category": "Media",
        "developer": "Plex",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": True,
    },
    "org.jellyfin.androidtv": {
        "name": "Jellyfin",
        "icon": "jellyfin.png",
        "brand_color": "#AA5CC3",
        "category": "Media",
        "developer": "Jellyfin",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": True,
    },
    "com.disney.disneyplus": {
        "name": "Disney+",
        "icon": "disneyplus.png",
        "brand_color": "#113CCF",
        "category": "Streaming",
        "developer": "Disney",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": False,
    },
    "com.amazon.amazonvideo.livingroom": {
        "name": "Prime Video",
        "icon": "primevideo.png",
        "brand_color": "#00A8E1",
        "category": "Streaming",
        "developer": "Amazon",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": False,
    },
    "com.hulu.livingroomplus": {
        "name": "Hulu",
        "icon": "hulu.png",
        "brand_color": "#1CE783",
        "category": "Streaming",
        "developer": "Hulu",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": True,
    },
    "com.max": {
        "name": "Max",
        "icon": "max.png",
        "brand_color": "#4B2EFF",
        "category": "Streaming",
        "developer": "Warner Bros.",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": False,
    },
    "org.xbmc.kodi": {
        "name": "Kodi",
        "icon": "kodi.png",
        "brand_color": "#17B2E7",
        "category": "Media",
        "developer": "Kodi Foundation",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": True,
    },
    "org.videolan.vlc": {
        "name": "VLC",
        "icon": "vlc.png",
        "brand_color": "#FF8800",
        "category": "Media",
        "developer": "VideoLAN",
        "supports_metadata": True,
        "supports_ads": False,
        "supports_live": True,
    },
}